### ISSUE TITLE
Wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql : exit status 1

### ISSUE THREAD

**Issue by Yersi88** [mvitale1989/helm-taiga#5]
I’m trying to deploy this on my rancher cluster and I keep getting this error and status “Installing”. Anyone can help me with this?

**Comment by mvitale1989** [comment]
I just released version 0.2.2 of the chart, which should solve this problem.
I also updated the readme to use most recent helm3. You can use those commands to bring up a test instance in the `default` namespace: https://github.com/mvitale1989/helm-taiga#tldr
Can you confirm if this solve the issue for you?

**Comment by Yersi88** [comment]
Thanks for updating the chart! Unfortunately, for me it's still the same error with version 0.2.2 and helm3 on Rancher :(

**Comment by mvitale1989** [comment]
@Yersi88 FYI i released version 0.2.3 of the chart with a further fix, feel free to check if it also solves your problem.

Note that with this new version, the `taiga.dbHost` value shouldn't be specified in your `values.yaml` anymore if you rely on the postgresql that gets installed by this chart. So you can remove it from your `values.yaml` before upgrading your installation.

**Comment by mvitale1989** [comment]
Assuming the issue is solved as there was no other feedback, closing
